export default {
  Flours: {},
  ["Herbs&Spices"]: {},
  Fruit: {},
  Grains: {},
  Vegetables: {},
  Dairy: {},
  Pantry: {},
  ["Canned&Jarred"]: {},
  Holiday: {},
  Oils: {},
  Protein: {},
  Citrus: {},
  Sweeteners: {},
  Condiments: {},
}
